### ISSUE TITLE
PLACK_ENV defaults to 'development'

### ISSUE THREAD

**Issue by haarg** [marcusramberg/Mojolicious-Plugin-MountPSGI#10]
This plugin doesn't set `PLACK_ENV` to any explicit value, so [Plack::Util::load_psgi](https://metacpan.org/source/MIYAGAWA/Plack-1.0047/lib/Plack/Util.pm#L133) defaults to 'development'.  It should be using the [Mojo app's mode](https://mojolicious.org/perldoc/Mojolicious#mode).

**Comment by jberger** [comment]
does it only matter during load_psgi or does it need to be set during requests too?

**Comment by haarg** [comment]
It's most important during load_psgi.  It should probably be set during the requests though.
