### ISSUE TITLE
Add CONTENT_LENGTH and CONTENT_TYPE to PSGI environment

### ISSUE THREAD

**Issue by mbudde** [marcusramberg/Mojolicious-Plugin-MountPSGI#5]
The [PSGI spec](http://search.cpan.org/~miyagawa/PSGI-1.102/PSGI.pod#The_Environment) requires that `CONTENT_LENGTH` and `CONTENT_TYPE` are passed in the PSGI environment. Currently POST form data is not being parsed by `CGI`/`CGI::PSGI` because of the missing content length.

**Comment by jberger** [comment]
For the record, those are required iff the header is present.
